version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  matrix:
    - nodejs_version: "22"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

build: off

test_script:
  - yarn test

artifacts:
  - path: dist
    name: my-artifacts

deploy:
  provider: GitHubPages
  username: <your_github_username>
  repository: <your_github_repository>
  branch: gh-pages
